# Generated by Django 6.0.3 on 2026-03-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_submissionstatus_report_excel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric_7_1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('participants_male', models.PositiveIntegerField(default=0)),
                ('participants_female', models.PositiveIntegerField(default=0)),
                ('participants_total', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric_7_1_11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=500)),
                ('duration_from', models.DateField(blank=True, null=True)),
                ('duration_to', models.DateField(blank=True, null=True)),
                ('participants_male', models.PositiveIntegerField(default=0)),
                ('participants_female', models.PositiveIntegerField(default=0)),
                ('participants_total', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric_7_1_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=300)),
                ('available', models.CharField(max_length=3)),
                ('beneficiaries', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric_7_1_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('locational_initiatives', models.PositiveIntegerField(default=0)),
                ('community_initiatives', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('initiative_name', models.CharField(max_length=500)),
                ('issues_addressed', models.TextField(blank=True)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric_7_1_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_of_publication', models.DateField(blank=True, null=True)),
                ('followup', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
